name: API Tests

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Subir MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: '7.0'

      - name: Verificar Secrets
        run: |
            echo "EMAIL_ADMIN existe? -> ${{ secrets.EMAIL_ADMIN != '' }}"
            echo "SENHA_ADMIN existe? -> ${{ secrets.SENHA_ADMIN != '' }}"
            echo "EMAIL_ALUNO existe? -> ${{ secrets.EMAIL_ALUNO != '' }}"
            echo "SENHA_ALUNO existe? -> ${{ secrets.SENHA_ALUNO != '' }}"

      - name: Run Tests
        run: npm test
